name: Sync Team Development to Company

on:
  push:
    branches:
      - development

jobs:
  sync-company:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Team Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Company Repository
        env:
          COMPANY_PAT: ${{ secrets.COMPANY_PAT }}
        run: |
          git clone https://x-access-token:${COMPANY_PAT}@github.com/AnushkaTakawale/DevOps-Task6-Industry-Workflow.git company-repo

      - name: Sync Files
        run: |
          rsync -av --delete \
            --exclude=".git" \
            --exclude="company-repo" \
            ./ company-repo/

      - name: Configure Git
        run: |
          cd company-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          cd company-repo
          git checkout development || git checkout -b development
          git add .
          git commit -m "Sync Team development to Company development" || echo "No changes to commit"
          git push origin development